version: '3.3'

volumes:
  icecream_local_postgres_data: { }
  icecream_local_postgres_data_backups: { }

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile

    image: icecream_local_django
    container_name: icecream_local_django
    volumes:
      - .:/app:z
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '8000:8000'
    command: /start
    networks:
      - tg_bot


  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
      - .:/usr/src/app/${BOT_NAME:-tg_bot}
    depends_on:
      - django
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
      - tg_bot

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: icecream_production_postgres
    container_name: icecream_local_postgres
    volumes:
      - icecream_local_postgres_data:/var/lib/postgresql/data
      - icecream_local_postgres_data_backups:/backups
    env_file:
      - .env
    networks:
      - tg_bot

networks:
  tg_bot:
    driver: bridge